name: CI/CD Pipeline for OTP Service with MySQL and Redis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: otpdb
        ports:
          - 3306:3306
        options: > 
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build Project with Maven
        working-directory: otp
        run: mvn clean install

      - name: Run Tests
        working-directory: otp
        env:
          DB_URL: jdbc:mysql://localhost:3306/otpdb
          DB_USER: root
          DB_PASSWORD: root
        run: mvn test
