name: CI/CD Pipeline for OTP Service with Redis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379 # Default Redis port

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust according to your project requirements

      - name: Build Project with Maven
        working-directory: otp
        run: mvn clean install

      - name: Run Tests
        working-directory: otp
        run: mvn test

      - name: Build Docker Image
        working-directory: otp
        run: |
          docker build -t otpwithredis:latest .

      - name: Push Docker Image to Docker Hub
        if: github.ref == 'refs/heads/main' # Optional: only push on main branch
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker tag otpwithredis:latest my-dockerhub-username/otpwithredis:latest
          docker push my-dockerhub-username/otpwithredis:latest
